{% set name = "solarmach" %}
{% set version = "0.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/solarmach-{{ version }}.tar.gz
  sha256: 53606ec84caabcedadc60dcac002609223a90e8916ffeb553c9c5b4f91b3df00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >={{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - astroquery
    - cmasher
    - drms
    - imageio >=2.31.5
    - jinja2
    - lxml
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - python-dateutil
    - scipy
    - setuptools
    - sunkit-magex
    - sunpy
    - zeep

test:
  imports:
    - solarmach
  requires:
    - python >={{ python_min }}
    - pip
    - flake8
    - pytest
    - pytest-doctestplus
    - pytest-cov
  commands:
    - pytest --pyargs solarmach.tests.test

about:
  home: https://github.com/jgieseler/solarmach
  summary: Multi-spacecraft longitudinal configuration plotter
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jgieseler
