{% set name = "solarmach" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solarmach-{{ version }}.tar.gz
  sha256: 573242f39f8f023e62afaa49090fb17ceb246aab43a84d2fc5cc055604e735d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.7
    - astropy
    - astroquery
    - cmasher
    - drms
    - imageio
    - jinja2
    - lxml
    - matplotlib-base ==3.5.3
    - numpy
    - pandas
    - pfsspy
    - plotly
    - python-dateutil
    - scipy
    - sunpy
    - zeep

test:
  imports:
    - solarmach
  requires:
    - pip
    - flake8
    - pytest
    - pytest-doctestplus
    - pytest-cov
  commands:
    - pytest --pyargs solarmach.tests.test

about:
  home: https://github.com/jgieseler/solarmach
  summary: Multi-spacecraft longitudinal configuration plotter
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jgieseler
