{% set name = "solarmach" %}
{% set version = "0.5.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/solarmach-{{ version }}.tar.gz
  sha256: 07b6e673e8d99f7572cf64acbc7a3944104a1fe9bc5ed9798158b3ca5a7b6626

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >={{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - cmasher
    - drms
    - imageio >=2.31.5
    - jinja2
    - lxml
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - python-dateutil
    - scipy
    - sunkit-magex
    - sunpy
    - threadpoolctl
    - zeep

test:
  imports:
    - solarmach
  requires:
    - python >={{ python_min }}
    - pip
    - flake8
    - pytest
    - pytest-doctestplus
    - pytest-cov
  commands:
    - pytest --pyargs solarmach.tests.test_solarmach

about:
  home: https://github.com/jgieseler/solarmach
  summary: Multi-spacecraft longitudinal configuration plotter
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jgieseler
