{% set name = "solarmach" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solarmach-{{ version }}.tar.gz
  sha256: 64dd9e9618ff67431b956cee21cbf0175be884ee9da6e3d6b466890288814e44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.10
    - astropy
    - cmasher
    - drms
    - imageio >=2.31.5
    - jinja2
    - lxml
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - python-dateutil
    - scipy
    - setuptools
    - sunkit-magex
    - sunpy
    - zeep

test:
  imports:
    - solarmach
  requires:
    - pip
    - flake8
    - pytest
    - pytest-doctestplus
    - pytest-cov
  commands:
    - pytest --pyargs solarmach.tests.test

about:
  home: https://github.com/jgieseler/solarmach
  summary: Multi-spacecraft longitudinal configuration plotter
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jgieseler
